# Generated by Django 4.2.3 on 2023-07-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='photo/')),
                ('aadhar_number', models.IntegerField(max_length=12)),
                ('aadhar_pdf', models.FileField(blank=True, null=True, upload_to='aadhar/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcode/')),
            ],
        ),
    ]
