# Generated by Django 4.2.3 on 2023-07-31 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('RvHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinfo',
            name='candidate_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='phone_number',
            field=models.IntegerField(max_length=64),
        ),
    ]
