# Generated by Django 4.2.3 on 2023-07-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvHub', '0002_candidateinfo_candidate_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='aadhar_pdf',
            field=models.FileField(blank=True, null=True, upload_to='aadhar'),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
